### ISSUE TITLE
Configuration File gets cleared by webpage

### ISSUE THREAD

**Issue by TomKimsey** [hms-networks/flexy-osisoft-connector#30]
When saving the configuration via the webpage interface the file is cleared on some systems.

**Comment by TomKimsey** [comment]
@oliver-walker-hms do you want to look into this issue?

**Comment by oliver-walker-hms** [comment]
I should be able to figure that out and push up a fix

________________________________

**Comment by TomKimsey** [comment]
@oliver-walker-hms have you looked into this yet?

**Comment by TomKimsey** [comment]
Investigated on 8/8/2019 and was unable to replicate issue.

**Comment by oliver-walker-hms** [comment]
configuration file is retired
