### ISSUE TITLE
GenericTypeBody always adds "format" key

### ISSUE THREAD

**Issue by it-hms** [hms-networks/flexy-osisoft-connector#81]
fix checking for types "string" and "boolean". if check will always evaluate to true. 

From function getGenericTypeBody, if expression always evaluate to true 
`
if (!type.equalsIgnoreCase("string") || !type.equalsIgnoreCase("boolean"))
`

**Comment by TomKimsey** [comment]
https://github.com/hms-networks/flexy-osisoft-connector/blob/67f861a4e65333aa0ce579938484fa5ca8ea55df/src/com/hms/flexyosisoftconnector/PayloadBuilder.java#L316
