### ISSUE TITLE
ContainerID max size Payload Builder

### ISSUE THREAD

**Issue by it-hms** [hms-networks/flexy-osisoft-connector#83]
Check maximum size for containerId. Sometimes this can cause an issue. 

https://github.com/hms-networks/flexy-osisoft-connector/blob/67f861a4e65333aa0ce579938484fa5ca8ea55df/src/com/hms/flexyosisoftconnector/PayloadBuilder.java#L437

**Comment by oliver-walker-hms** [comment]
this seems to have been falsely diagnosed by one of our users. There was an issue where the type id was updated to include the tag type and flexy serial number for uniqueness but the container referencing that type was not updated. updating the container id fixed this issue
