### ISSUE TITLE
Releases included uneeded Jar file

### ISSUE THREAD

**Issue by it-hms** [hms-networks/flexy-osisoft-connector#84]
releases since 2.4 include 3MB google-java-format-1.8-all-deps.jar. Remove this from build/release process.

**Comment by TomKimsey** [comment]
@it-hms where are you seeing this? I checked 2.4 2.5 and 2.6 and did not see google-java-format-1.8-all-deps.jar in any of the releases.

**Comment by oliver-walker-hms** [comment]
it's in the jar file itself under src/com/flexyosisoftconnector
I'm pretty sure it's eclipse adding it in since the script uses the same build file

**Comment by TomKimsey** [comment]
> it's in the jar file itself under src/com/flexyosisoftconnector
> I'm pretty sure it's eclipse adding it in since the script uses the same build file

Okay, yeah that should be removed then especially since its packaged in the connector jar.
