### ISSUE TITLE
make release script

### ISSUE THREAD

**Issue by it-hms** [hms-networks/flexy-osisoft-connector#95]
For consistent releases, create release script. Consider using github actions.

**Comment by TomKimsey** [comment]
Currently releases should already be generated via a release script. https://github.com/hms-networks/flexy-osisoft-connector/blob/master/tools/MakeRelease.py

**Comment by TomKimsey** [comment]
https://github.com/hms-networks/flexy-aws-connector/blob/master/.github/workflows/aws-release-built.yml

@oliver-walker-hms if you do switch to github actions (which preferred as you are guaranteed the build matches the code at that tag) you can use this yaml as an example.

**Comment by oliver-walker-hms** [comment]
They are generated through a python script. Github actions would be more inline with the other connectors.
