### ISSUE TITLE
Simplify config file 

### ISSUE THREAD

**Issue by it-hms** [hms-networks/flexy-osisoft-connector#96]
Change "IP" parameter to "URL".  Remove "proxyURL". This is just confusing.  Also, do not dictate scheme, just let users put the full url in the config file.

**Comment by oliver-walker-hms** [comment]
I agree IP should be called URL. The endpoint for each API is slightly different and having the user specify that would add in possible confusion.

Also, one of our large customers requires a proxy URL and that should probably be at the least a hidden configuration that we support.
